import constants.llms as llm_const

OPENAI_EMBEDDING_SMALL = "text-embedding-3-small"
OPENAI_EMBEDDING_LARGE = "text-embedding-3-large"
OPENAI_EMBEDDING_ADA = "text-embedding-ada-002"

GOOGLE_EMBEDDING_004 = "models/text-embedding-004"
GOOGLE_EMBEDDING_001 = "models/embedding-001"

GOOGLE_EMBEDDING_MODELS = [GOOGLE_EMBEDDING_004, GOOGLE_EMBEDDING_001]
OPENAI_EMBEDDING_MODELS = [
    OPENAI_EMBEDDING_SMALL,
    OPENAI_EMBEDDING_LARGE,
    OPENAI_EMBEDDING_ADA,
]
EMBEDDING_MODELS = {
    llm_const.GOOGLE: GOOGLE_EMBEDDING_MODELS,
    llm_const.OPENAI: OPENAI_EMBEDDING_MODELS,
}
